FROM ubuntu:18.04
LABEL author="zqj"
ENV PYTHONIOENCODING=utf-8

#ADD sources.list /etc/apt/

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing && \
    apt-get install -y --fix-missing --no-install-recommends \
            software-properties-common \
            autoconf \
            automake \
            build-essential \
            libboost-all-dev \
            libgsl0-dev \
            libeigen3-dev \
            curl \
            cmake \
            git \
            libcurl3-dev \
            libopencv-dev \
            libopencv-core-dev \
            libtool \
            pkg-config \
            python \
            python-pip \
            python3 \
            python3-dev  \
            python3-pip \
            nginx \
            goaccess \
            supervisor &&  \
    ldconfig
RUN pip3 install --no-cache-dir --upgrade setuptools pip -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN mkdir -p /deploy/app
WORKDIR /deploy/app
COPY ./requirements.txt /deploy/app/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /deploy/app/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple  --timeout 600
# Setup nginx
RUN rm /etc/nginx/sites-enabled/default
COPY ./nginx_flask.conf /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/nginx_flask.conf /etc/nginx/sites-enabled/nginx_flask.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
# timezone
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && rm -rf /var/lib/apt/lists/*
CMD ["bash"]
